### ISSUE TITLE
Error when using mapbox geocoder

### ISSUE THREAD

**Issue by argenisleon** [veltman/address-book#12]
Hi,

I getting this error when using mapbox geocoder.

csvgeocode.js:161
    } else if ("lat" in result && "lng" in result) {
                        ^

TypeError: Cannot use 'in' operator to search for 'lat' in undefined
    at handleResponse (C:\Users\argenis\AppData\Roaming\npm\node_modules\csvgeocode\src\csvgeocode.js:161:25)
    at Request._callback (C:\Users\argenis\AppData\Roaming\npm\node_modules\csvgeocode\src\csvgeocode.js:133:9)
    at Request.self.callback (C:\Users\argenis\AppData\Roaming\npm\node_modules\csvgeocode\node_modules\request\request.
js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\argenis\AppData\Roaming\npm\node_modules\csvgeocode\node_modules\request\request.js
:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\argenis\AppData\Roaming\npm\node_modules\csvgeocode\node_modules\request\re
quest.js:963:12)
    at emitNone (events.js:72:20)

When I use the url in the browser I get.

{"type":"FeatureCollection","query":["maracaibo"],"features":[{"id":"place.15865","type":"Feature","text":"Maracaibo","place_name":"Maracaibo, Zulia, Venezuela","relevance":0.99,"properties":{},"bbox":[-71.7817466,10.582766,-71.586462,10.7688503],"center":[-71.6407,10.6436],"geometry":{"type":"Point","coordinates":[-71.6407,10.6436]},"context":[{"id":"region.5652266462607880","text":"Zulia"},{"id":"country.13795682694360550","text":"Venezuela","short_code":"ve"}]},{"id":"place.15864","type":"Feature","text":"Maracaibo","place_name":"Maracaibo, Valle del Cauca, Colombia","relevance":0.99,"properties":{},"bbox":[-76.5181048,3.4174864,-76.5159618,3.4195548],"center":[-76.517063,3.418486],"geometry":{"type":"Point","coordinates":[-76.517063,3.418486]},"context":[{"id":"region.13115541496430840","text":"Valle del Cauca"},{"id":"country.8835466213820440","text":"Colombia","short_code":"co"}]},{"id":"address.3991858998015520","type":"Feature","text":"Rua Maracaibo","place_name":"Rua Maracaibo, Santo André, São Paulo 09250, Brazil","relevance":0.79,"properties":{},"center":[-46.520427,-23.623473],"geometry":{"type":"Point","coordinates":[-46.520427,-23.623473]},"context":[{"id":"place.24117","text":"Santo André"},{"id":"postcode.1287776102566740","text":"09250"},{"id":"region.6056669612838220","text":"São Paulo"},{"id":"country.17318012316682710","text":"Brazil","short_code":"br"}]},{"id":"address.3219787327733630","type":"Feature","text":"Privada Maracaibo","place_name":"Privada Maracaibo, Ecatepec de Morelos, México, Mexico","relevance":0.79,"properties":{},"center":[-99.016035,19.593392],"geometry":{"type":"Point","coordinates":[-99.016035,19.593392]},"context":[{"id":"place.7221","text":"Ecatepec de Morelos"},{"id":"region.5989025148456720","text":"México"},{"id":"country.11735183656773450","text":"Mexico","short_code":"mx"}]},{"id":"address.9663854498015520","type":"Feature","text":"Rua Maracaibo","place_name":"Rua Maracaibo, Porto Alegre, Rio Grande Do Sul 91225, Brazil","relevance":0.79,"properties":{},"center":[-51.1345179,-30.0127374],"geometry":{"type":"Point","coordinates":[-51.1345179,-30.0127374]},"context":[{"id":"place.20332","text":"Porto Alegre"},{"id":"postcode.11986695081151740","text":"91225"},{"id":"region.4633809344890480","text":"Rio Grande Do Sul"},{"id":"country.17318012316682710","text":"Brazil","short_code":"br"}]}],"attribution":"NOTICE: © 2016 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained."}

Any help?

**Comment by veltman** [comment]
I'm not able to replicate this.  Are you sure your URL is formatted correctly and you're supplying "mapbox" as the handler?  Can you provide the exact command you're running and a row from the source file?

For example, with the following CSV:

```
row,address
1,maracaibo
```

And the following command:

```
csvgeocode --url "http://api.tiles.mapbox.com/v4/geocode/mapbox.places/{{address}}.json?access_token=INSERT_YOUR_API_KEY" --handler mapbox input.csv
```

It seems to work.

**Comment by fitnr** [comment]
I got this error because I omitted the `--handler` option. It might be nice if the cli used the url for handler hinting, at least for the defaults.

**Comment by veltman** [comment]
That kinda makes sense but I am reluctant to put much magic code in there, especially since the relevant URL patterns might change.  I think keeping the URL + handler separate is a little more maintainable.

**Comment by veltman** [comment]
I added a small change in 54dfff7ecfc091b120 so that you'll at least see a warning if you omit the option.
