### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by zzolo** [veltman/address-book#3]
Maybe I missed something, but it would be cool to use streams/pipes.  And not because they are all the rage.  The specific use case is that if I have a file with 5000 addresses and I want to geocode with Google, I'll run into the 24 hour limit.  It would be great to do a run that saves what has been done so that I can come back to it later and finish it.

**Comment by zzolo** [comment]
Actually, it looks like my use case is covered.  It still puts in an empty row if the query limit is reached.

**Comment by veltman** [comment]
It started out using streams but that made throttling/queueing requests a lot trickier so I gutted them back out.  In terms of having too many to run, yeah, it should successfully run some and just fail on the rest.  You should be able to pass the same file back through multiple times to fill in more blank rows.
